name: SBOM Security Pipeline
on:
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    
    - name: Scan current project
      uses: anchore/scan-action@v3
      id: scan
      with:
        path: "."

    - name: Create SBOM
      uses: anchore/sbom-action@v0
      with:
        format: spdx-json
        output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    

